name: Continuous coverage and quality analysis

on:
  push:
  pull_request:

jobs:
  test-and-quality:
    name: Coverage & Quality analysis
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: setup-python
        name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.13"
          cache: "pip"

      - id: install-venv
        name: Install virtual environment
        run: make venv-clean venv-install

      - id: run-tests-with-coverage
        name: Run unit tests with coverage
        run: make venv-test-coverage-xml

      - id: upload-coverage-report
        name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-report
          path: coverage.xml

      - id: upload-coverage
        name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: code-quality
        name: Code quality
        run: make venv-lint