name: Continuous building and testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: Building & Testing
    runs-on: ubuntu-latest

    permissions:
      # For publishing the test report
      contents: write       # for gh-pages
      checks: write         # for test status publish

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: setup-python
        name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.12"
          cache: "pip"

      - id: install-venv
        name: Install virtual environment
        run: |
          make venv-clean venv-install

      - id: run-tests
        name: Run unit tests with unittest and BDD scenarios
        run: |
          make venv-test-action
